### ISSUE TITLE
Error saving Homepage

### ISSUE THREAD

**Issue by lboaretto** [caddis/craft-presto#18]
PHP notice
Undefined offset: 1

Parts of stacktrace:

`/home/forge/domain.com/craft/plugins/presto/services/PrestoService.php(120)`
108     public function purgeCache($paths = [])
109     {
110         if (count($paths)) {
111             foreach ($paths as $path) {
112                 $url = explode('|', $path, 2);
113 
114                 $targetPath = IOHelper::folderExists(
115                     $this->normalizePath(implode('/', [
116                         $this->rootPath,
117                         $this->settings->cachePath,
118                         $url[0],
119                         'presto',
**120                         str_replace('home', '', $url[1])**
121                     ]))
122                 );
123 
124                 $targetFile = IOHelper::fileExists($targetPath . '/index.html');
125 
126                 if ($targetFile) {
127                     @unlink($targetFile);
128                 }
129 
130                 if ($targetPath) {
131                     @rmdir($targetPath);
132                 }

 `/home/forge/domain.com/craft/plugins/presto/PrestoPlugin.php(130): Craft\PrestoService->purgeCache(array("uRkV8iQtdtzvle9zf3Wm9ZXDTxVigoQdus6C", "1wLFki09OEOOjsAmepj8BiSb8PCOddHJHv4x", "domain.com|home"))`

125         } elseif (count($caches) || $this->caches) {
126             $caches = count($caches) ? $caches : $this->caches;
127 
128             if ($immediate) {
129                 craft()->presto->purgeCache(
**130                     craft()->presto->formatPaths($caches)**
131                 );
132             } else {
133                 craft()->presto->storePurgeEvent(
134                     craft()->presto->formatPaths($caches)
135                 );

Complete stacktrace: https://codepen.io/lboaretto/pen/LzYZwL

**Comment by ryanbrookepayne** [comment]
@lboaretto Please provide more information:

- What did you do to replicate this error?
- How is your homepage setup in the CMS?

**Comment by lboaretto** [comment]
Hi @ryanbrookepayne 

There is not much complexity. 

I have only one Neo field called "Slide", which would be the same as using Matrix to insert some featured content on home:

Entry, Title (to overwrite entry title), Slide Image (to overwrite Entry image)

In the complete stacktrace, can you see anything?

**Comment by ryanbrookepayne** [comment]
@lboaretto Are you using a single for your homepage?

**Comment by lboaretto** [comment]
@ryanbrookepayne Yes! Homepage single

I use Neo fields on Channel and I had no problems.

**Comment by ryanbrookepayne** [comment]
@lboaretto Try purging your entire cache in the settings page. Looks like there is a mixture of native craft and presto template caching keys which is causing the index issue.

**Comment by lboaretto** [comment]
@ryanbrookepayne After manual (settings page) purging entire cache, I was able to save the homepage again...

**Comment by ryanbrookepayne** [comment]
@lboaretto Glad I could help. Let me know if you have any additional issues.

**Comment by lboaretto** [comment]
Thank you @ryanbrookepayne
