### ISSUE TITLE
Rows in the craft template cache db tables are not being cleared correctly

### ISSUE THREAD

**Issue by ryanbrookepayne** [caddis/craft-presto#3]
@thechrisroberts @nathanhood The craft template db rows and the cached files are getting out of sync.

**Comment by thechrisroberts** [comment]
Could use additional info. Craft's internal cache should clear as they always have, with the static cache files only getting purged when the cron job runs. In the interim, there will be an inconsistency.  And the cron command doesn't touch the craft cache, only the static files generated by Presto.
