### ISSUE TITLE
Cached template files are not being cleared

### ISSUE THREAD

**Issue by ryanbrookepayne** [caddis/craft-presto#4]
Presto is trying to clear the cache with a console command. The console command is run in the project root. The console command tries to clear the cache in the "/cache" directory instead of the "/public_html/cache" directory. This is because `$_SERVER['DOCUMENT_ROOT']` returns an empty string.

**Comment by thechrisroberts** [comment]
Presto should be adding a plugin setting `rootPath` that matches the `rootPath` being used via the web. This was added to address the issue of DOCUMENT_ROOT being unavailable via command line. If the setting isn't being added for you, something else is going on. But as a fallback option, you can create a config/presto.php file and set `rootPath` there with the full path to the cache folder.
