### ISSUE TITLE
Updating from v.0.5.0 to v.0.6.0 causes error when pushing to staging server

### ISSUE THREAD

**Issue by ryanbrookepayne** [caddis/craft-presto#6]
@thechrisroberts I am able to update locally, but when I push to a staging server, I get the following error. Do you need to check for the existence of the table you are inserting?

This isn't urgent, just needs to be fixed before we make a release.

![craft presto update error](https://cloud.githubusercontent.com/assets/12212345/23874795/ec9bd8ea-0804-11e7-82e6-39a52b12bcfd.png)

**Comment by ryanbrookepayne** [comment]
@thechrisroberts This issue has not been resolved. It's not related to the environment setup. It's when I push the update into gitflow and run "Finish Up" on the CMS to update the db.

**Comment by thechrisroberts** [comment]
Can you provide additional details? Checking for the table shouldn't be needed since Craft won't run the migration more than once. If you were doing the upgrade off a previous test of this Presto update, that could explain it.

**Comment by ryanbrookepayne** [comment]
@thechrisroberts I'll just have to test it on Craft base and let you know. It may have been a BT specific issue.
